### ISSUE TITLE
Suggestion - Please support the official instances for the Teddit and Libreddit front-ends

### ISSUE THREAD

**Issue by ghost** [revddit/revddit-linker#7]
Teddit (https://teddit.net - for the old experience) and Libreddit (https://libredd.it - for the new experience) are private front-ends. These projects may be self-hosted, but their official instances are healthy and most likely to withstand the test of time.

Please support these two URLs in a future version of reveddit-linker!

**Comment by rhaksw** [comment]
Hi, you're more than welcome to submit a PR for this. Thanks!
